### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dairosaal** [m8r0wn/enumdb#3]
Hello, I've installed all libs and tested on my localhost, but it doesnt works.

Starting enumdb v2.0.1
-------------------------
[-] Login failed root:123@xxx.xxx.xxx.xxx

Everytime and every server that I tried I got this. Do you what it can be?

**Comment by dairosaal** [comment]
Wrong sintaxe on connect function

**Comment by m8sec** [comment]
Hi @dairosaal,
Can you provide the type of database you are trying this on? You mentioned you tested this on your local host, if this is mysql, try 'localhost' instead of '127.0.0.1':
```bash
python3 enumdb.py -u root -p '123' -t mysql localhost
```
-m8r0wn

**Comment by m8sec** [comment]
If the issue persists please let me know
-m8r0wn
