### ISSUE TITLE
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes

### ISSUE THREAD

**Issue by ycathi** [m8r0wn/enumdb#4]
[root@localhost enumdb]# `python enumdb.py `
  File "enumdb.py", line 421
        ** Having trouble with inputs? Use '' around username & password **""".format(argv[0], version), formatter_class=argparse.RawTextHelpFormatter, usage=argparse.SUPPRESS)
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 447-448: truncated \uXXXX escape

Can't run in termux……
view `https://github.com/termux/termux-packages`
view `https://github.com/sdrausty/TermuxArch`

The same error all the time
![_20181114222838](https://user-images.githubusercontent.com/38828027/48488907-c4ba9e80-e85c-11e8-8dfe-38f6d4c3af58.png)

**Comment by m8sec** [comment]
Hi @ycathi,
Oh no! I was able to replicate the issue and think we have it addressed. Please let me know if there are any more issues with the program. Thank you for your help!
-m8r0wn

**Comment by ycathi** [comment]
@m8r0wn Sorry, too busy today

1、In `TermuxArach` , the `MySQLdb.connect` is use like this
`con = MySQLdb.connect(host=host, user=user, password=passwd)`

2、Another problem is `pymssql` ，there is no packages

[root@localhost enumdb]# `pacman -Ss mssql`
[root@localhost enumdb]# 

So I annotated the code 

`#import pymssql`

3、After modification，It works.

Thanks.

**Comment by ycathi** [comment]
1、In `Termux` ,  you can install mysql support by `pip`
`pip install pymysql` 
if error happens
`apt install lib* lib*dev`
and try again
`pip install pymysql` 

2、replace MySQLdb in enumdb.py
`perl -pi -e 's/MySQLdb/pymysql/g'` enumdb.py

3、And so, install openpyxl like this
`pip install openpyxl`

4、But，there is a problem
![_20181117125357](https://user-images.githubusercontent.com/38828027/48657098-2bf86e80-ea68-11e8-82e6-cccffcb790be.png)

em， single password is correct
![sss](https://user-images.githubusercontent.com/38828027/48657145-74179100-ea68-11e8-8252-659d4d690d46.png)

**Comment by m8sec** [comment]
Hi @ycathi,

This is great information for users attempting to use enumdb from Termux. The original issue  pertained to all users and has since been addresses. However, I am going to label this as an enhancement and work on getting a dev environment setup to potentially add a setup script for Termux. I also want to look into some of the pip/pip3 concerns to see if we can get mssql working for those users as well. Pull requests welcome :)

Thank you for the help,
m8r0wn

**Comment by m8sec** [comment]
Pull requests welcome, but unfortunately I don't have the time to research this potential improvement right now. Closing issue.

-m8r0wn
