### ISSUE TITLE
Thread(target=enum_db().db_main, args=(args, t,), daemon=True).start()

### ISSUE THREAD

**Issue by Prostu2** [m8r0wn/enumdb#5]
root@hw1-live:/srv/qwe/sqli-scanner/sqliv/enumdb# python enumdb.py -u root -p Password1 -brute 127.0.0.1 -t mssql

Starting enumdb v2.0.4
-------------------------
Traceback (most recent call last):
  File "enumdb.py", line 446, in <module>
    main(args)
  File "enumdb.py", line 395, in main
    Thread(target=enum_db().db_main, args=(args, t,), daemon=True).start()
TypeError: __init__() got an unexpected keyword argument 'daemon'
root@hw1-live:/srv/qwe/sqli-scanner/sqliv/enumdb#

**Comment by m8sec** [comment]
Hi@Prostu2,

Enumdb only supports Python3

Thanks,
m8r0wn
