### ISSUE TITLE
No module named 'MySQLdb'

### ISSUE THREAD

**Issue by smileronin** [m8r0wn/enumdb#7]
help for Following issue. Thanks.

$ python3 enumdb.py
Traceback (most recent call last):
  File "enumdb.py", line 7, in <module>
    import MySQLdb
ImportError: No module named 'MySQLdb'

**Comment by m8sec** [comment]
Hi @smileronin,
 
Have you installed the requirements during installation? and what OS are you using?

```
git clone https://github.com/m8r0wn/enumdb
cd enumdb
pip3 install -r setup/requirements.txt
```

**Comment by smileronin** [comment]
Hi m8r0wn,
Firstly, respect for your working. But, if only python3 had no dependency, because when app is working, python3 create really depency problem,  python3 is already problem, already error
I tried 2 different OS Ubuntu and Kali, python 3.5 version install in my OS system, I install requirements.txt, but, I get same error such as following. 
If I find any solution, I will try new fresh  Linux OS Install

Traceback (most recent call last):
File "enumdb.py", line 7, in
import MySQLdb
ImportError: No module named 'MySQLdb'

 Actually, i think

**Comment by m8sec** [comment]
hmm it should be fine on Ubuntu and Kali, but I am also running Python 3.7. Try using the backup bash script to install the dependencies. This will use apt-get install of pip3:

```bash
git clone https://github.com/m8r0wn/enumdb
cd enumdb/setup
sudo bash setup.sh
```

**Comment by smileronin** [comment]
yes, with sudo bash setup.sh, it's resolved. Thank you very much.

**Comment by m8sec** [comment]
No problem, glad we got it solved!
