### ISSUE TITLE
create setup.py and support system wide installation

### ISSUE THREAD

**Issue by blshkv** [m8r0wn/enumdb#8]
You should get rid of setup.sh and use setup.py to unify the installation for any Linux distribution.
Then, the following command should be used:
```python setup.py install {--user}```

All output of the tool should be redirected to ```~/.enumdb``` or similar.

**Comment by m8sec** [comment]
Hi @blshkv,

I 100% agree about the setup file, the requirements.txt was supposed to be a trial run to see if all dependencies can be installed that way. I just resolved Issue #7 by telling them to revert back to the setup.sh file. There seems to be inconsistencies installing the MySQLdb package ill have to look into further.

Appreciate the feedback about output, ive been needing to cleanup the output formatting/reporting. Always good to know others are paying attention :)

**Comment by blshkv** [comment]
My point is very different what you mentioned in the issue. You should not have ```setup.sh``` at all, leave this job for a distro packet manager.

The enumdb should be ported to each linux repository, so the end user could simple run ```apt-get install enumdb``` or ```emerge enumdb``` under Pentoo Linux.

setup.py is the only file which is really required for the proper packaging.

**Comment by blshkv** [comment]
https://github.com/derv82/wifite2/issues/102

**Comment by m8sec** [comment]
Understood, my initial goal was to create a setup.py file and add the project to PyPi. This would resolve the issue for a simple installation/removal process with ```pip3 install enumdb``` and be easier from a management perspective as well. This would also contribute to the latest open issue #9 of creating proper releases. 

In my previous message, I was trying to convey issues with package resources that was limiting this. However, I believe this has been solved and I am working on a setup.py file now.

**Comment by blshkv** [comment]
Great, thank you!

**Comment by m8sec** [comment]
Just did a push with the new ```setup.py``` file, will keep the issue open until I've had a chance to add it to PyPi. 

Haven't forgotten about the output suggestions, but may need to save that for a later update :)

**Comment by m8sec** [comment]
Alright were good to go, it is up on PyPi and ``` pip3 install enumdb``` is working.

Thanks again for your feedback!
\- m8r0wn

**Comment by blshkv** [comment]
well done, thanks for working on this tool
